# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'GithubAPIAssignment' do
  use_frameworks!

  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'Toast-Swift'

end
